export default {
  'body-background': 'whitesmoke',
  'mp-header-background': 'black',
  'mp-header-height': '65px',
  'mp-header__logoTitle-color': 'white',
  'mp-header__menuItem-fontSize': '12px',
  'mp-header__menuItem-color': 'white',
  'mp-header__menuItem-active': 'rgb(86, 132, 255)',
  'mp-header__menuItem-hover': 'rgb(126, 182, 255)',
  'mp-page-products-searchbox_border': '1px solid lightgray',
  'mp-products-search_bg': 'white',
  'mp-page-products-searchIcon': 'black',
  'mp-product-filter_header-border': '1px solid rgb(230, 230, 230)',
  'p-product-filter_title_fontsize': '14px',
  products_list_filters_background: 'goldenrod',
  products_list_filters_color: 'black',
  products_list_filters_titleFontSize: '13px',
  products_list_filters_iconFfontSize: '11px',
  'mp-product-category_title_fontsize': '14px',
  'mp-product-category_active_color': 'rgb(56, 132, 255)',
  'mp-product-category_count_fontsize': '13px',
  'mp-product-category_title_color': 'gray',
  'mp-product-contentType_fontsize': '14px',
  'mp-product-contentType_radio_bg': 'rgb(56, 132, 255)',
  'products-right-header-border': '0.5px solid lightgray',
  'products-list-header-title': '22px',
  'products-list-item-bg': 'white',
  'products-list-item-border': '0.5px solid whitesmoke',
  'products-detail-media-border': '0.5px solid lightgray',
  'products-detail-media-bg': 'white',
  'products-detail-attachment-bg': 'white',
  'products-detail-attachment-unknow-fontSize': "18px",
  'products-detail-attachment-border': "2px solid lightgray",
  'products-detail-attachment-active-border': "2px solid rgb(56, 132, 255)",
  'products-detail-attachment-activeCircle-bg': "rgb(56, 132, 255)",
  'products-detail-attachment-activeCircle-color': "white !important",
}
